import { notFound, permanentRedirect } from "next/navigation";
import { InsightArticle } from "../../../components/InsightArticle";
import { StructuredData } from "../../../components/StructuredData";
import { getPublishedInsightBySlug, getRelatedInsights, listAuthors, listCategories, resolveInsightRedirect } from "../../../lib/server/insightsRepository";
import { absoluteUrl, DEFAULT_OG_IMAGE } from "../../../lib/seo";

export const dynamic="force-dynamic";

export async function generateMetadata({params}){const {slug}=await params;const post=await getPublishedInsightBySlug(slug);if(!post)return {title:'Insight Not Found',robots:{index:false,follow:false}};return {title:post.seo?.title||post.title,description:post.seo?.description||post.excerpt,alternates:{canonical:post.seo?.canonicalUrl||absoluteUrl(`/insights/${post.slug}`)},robots:{index:post.seo?.allowIndexing!==false,follow:true},openGraph:{type:'article',title:post.seo?.title||post.title,description:post.seo?.description||post.excerpt,url:absoluteUrl(`/insights/${post.slug}`),publishedTime:post.publishedAt,modifiedTime:post.updatedAt,images:[post.seo?.openGraphImage||post.featuredImage?.url||DEFAULT_OG_IMAGE]},twitter:{card:'summary_large_image',title:post.seo?.title||post.title,description:post.seo?.description||post.excerpt,images:[post.seo?.openGraphImage||post.featuredImage?.url||DEFAULT_OG_IMAGE]}}}

export default async function InsightPage({params}){const {slug}=await params;const [post,categories,authors]=await Promise.all([getPublishedInsightBySlug(slug),listCategories(),listAuthors()]);if(!post){const redirectPath=await resolveInsightRedirect(slug);if(redirectPath)permanentRedirect(redirectPath);notFound();}const [relatedPosts]=await Promise.all([getRelatedInsights(post,3)]);const author=authors.find(item=>item.id===post.authorId);const schema={"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.excerpt,datePublished:post.publishedAt,dateModified:post.updatedAt||post.publishedAt,mainEntityOfPage:absoluteUrl(`/insights/${post.slug}`),author:{"@type":"Organization",name:author?.name||post.authorName||'GrowVest Editorial Team'},publisher:{"@type":"Organization",name:'GrowVest',url:absoluteUrl('/')},image:post.featuredImage?.url||DEFAULT_OG_IMAGE};return <><StructuredData id={`insight-${post.id}`} data={schema}/><InsightArticle post={post} author={author} categories={categories} relatedPosts={relatedPosts}/></>}
