import { FieldValue } from "firebase-admin/firestore";

export async function writeCommunicationLog(db, {
  requestId,
  subscriberId,
  leadKey,
  entityType,
  entityId,
  channel = "email",
  type,
  templateKey,
  direction = "outbound",
  recipient,
  status,
  provider = "brevo",
  providerMessageId,
  providerCode,
  errorMessage,
  sentBy,
  sentByName,
  subject,
  metadata,
}) {
  await db.collection("communicationLogs").add({
    requestId: requestId || null,
    subscriberId: subscriberId || null,
    leadKey: leadKey || null,
    entityType: entityType || null,
    entityId: entityId || null,
    channel,
    type,
    templateKey: templateKey || null,
    direction,
    recipient,
    subject: subject ? String(subject).slice(0, 180) : null,
    status,
    provider,
    providerMessageId: providerMessageId || null,
    providerCode: providerCode || null,
    errorMessage: errorMessage ? String(errorMessage).slice(0, 500) : null,
    sentBy: sentBy || null,
    sentByName: sentByName || null,
    metadata: metadata || null,
    createdAt: FieldValue.serverTimestamp(),
  });
}
